/*
# Copyright (C) 2023, Sorbonne Universite, LIP6
# This file is part of the VerifMSI project, under the GPL v3.0 license
# See https://www.gnu.org/licenses/gpl-3.0.en.html for license information
# SPDX-License-Identifier: GPL-3.0-only
# File generated by generate_isw_and.py
*/


#include "verif_msi_pp.hpp"


int order = 3;
SecurityProperty secProp = NI;
bool withGlitches = false;
bool dumpCirc = false;
bool checkFunctionality = false;
const char * circuitFilename = "circuit.dot";


int isw_and_4_shares() {

    Node & a = symbol("a", 'S', 1);
    Node & b = symbol("b", 'S', 1);

    std::vector<Node *> u = getRealShares(a, 4);
    std::vector<Node *> v = getRealShares(b, 4);

    Node & _a0 = *u[0];
    Node & _a1 = *u[1];
    Node & _a2 = *u[2];
    Node & _a3 = *u[3];

    Node & _b0 = *v[0];
    Node & _b1 = *v[1];
    Node & _b2 = *v[2];
    Node & _b3 = *v[3];


    HWElement & a0 = inputGate(_a0);
    HWElement & a1 = inputGate(_a1);
    HWElement & a2 = inputGate(_a2);
    HWElement & a3 = inputGate(_a3);
    HWElement & b0 = inputGate(_b0);
    HWElement & b1 = inputGate(_b1);
    HWElement & b2 = inputGate(_b2);
    HWElement & b3 = inputGate(_b3);

    Node & _z0_1 = symbol("z0_1", 'M', 1);
    HWElement & z0_1 = inputGate(_z0_1);
    HWElement & a0b1 = andGate(a0, b1);
    HWElement & a1b0 = andGate(a1, b0);
    HWElement & z1_0 = xorGate(xorGate(z0_1, a0b1), a1b0);
    Node & _z0_2 = symbol("z0_2", 'M', 1);
    HWElement & z0_2 = inputGate(_z0_2);
    HWElement & a0b2 = andGate(a0, b2);
    HWElement & a2b0 = andGate(a2, b0);
    HWElement & z2_0 = xorGate(xorGate(z0_2, a0b2), a2b0);
    Node & _z0_3 = symbol("z0_3", 'M', 1);
    HWElement & z0_3 = inputGate(_z0_3);
    HWElement & a0b3 = andGate(a0, b3);
    HWElement & a3b0 = andGate(a3, b0);
    HWElement & z3_0 = xorGate(xorGate(z0_3, a0b3), a3b0);
    Node & _z1_2 = symbol("z1_2", 'M', 1);
    HWElement & z1_2 = inputGate(_z1_2);
    HWElement & a1b2 = andGate(a1, b2);
    HWElement & a2b1 = andGate(a2, b1);
    HWElement & z2_1 = xorGate(xorGate(z1_2, a1b2), a2b1);
    Node & _z1_3 = symbol("z1_3", 'M', 1);
    HWElement & z1_3 = inputGate(_z1_3);
    HWElement & a1b3 = andGate(a1, b3);
    HWElement & a3b1 = andGate(a3, b1);
    HWElement & z3_1 = xorGate(xorGate(z1_3, a1b3), a3b1);
    Node & _z2_3 = symbol("z2_3", 'M', 1);
    HWElement & z2_3 = inputGate(_z2_3);
    HWElement & a2b3 = andGate(a2, b3);
    HWElement & a3b2 = andGate(a3, b2);
    HWElement & z3_2 = xorGate(xorGate(z2_3, a2b3), a3b2);

    HWElement & c0a = andGate(a0, b0);
    HWElement & c0b = xorGate(c0a, z0_1);
    HWElement & c0c = xorGate(c0b, z0_2);
    HWElement & c0 = xorGate(c0c, z0_3);
    HWElement & c1a = andGate(a1, b1);
    HWElement & c1b = xorGate(c1a, z1_0);
    HWElement & c1c = xorGate(c1b, z1_2);
    HWElement & c1 = xorGate(c1c, z1_3);
    HWElement & c2a = andGate(a2, b2);
    HWElement & c2b = xorGate(c2a, z2_0);
    HWElement & c2c = xorGate(c2b, z2_1);
    HWElement & c2 = xorGate(c2c, z2_3);
    HWElement & c3a = andGate(a3, b3);
    HWElement & c3b = xorGate(c3a, z3_0);
    HWElement & c3c = xorGate(c3b, z3_1);
    HWElement & c3 = xorGate(c3c, z3_2);

    if (checkFunctionality) {
        std::map<Node *, Node *> values;
        uint64_t v0, v1;
        bool res = compareExpsWithExev(c0.getSymbExp() ^ c1.getSymbExp() ^ c2.getSymbExp() ^ c3.getSymbExp(), a & b, values, &v0, &v1);
        if (res) {
            std::cout << "# functionality (exhaustive evaluation): [OK]" << std::endl;
        }
        else {
            std::cout << "# functionality (exhaustive evaluation): [KO]" << std::endl;
            for (const auto & [k, v] : values) {
                std::cout << "# value of " << *k << ": " << *v << std::endl;
            }
        }
    }

    if (dumpCirc) {
        std::vector<HWElement *> outputs {&c0, &c1, &c2, &c3};
        dumpCircuit("circuit.dot", outputs);
    }

    std::vector<HWElement *> outputs {&c0, &c1, &c2, &c3};
    int nbLeak = checkSecurity(order, withGlitches, secProp, outputs);
    return nbLeak;
}


int main() {
    int nbLeak = isw_and_4_shares();
    std::cout << "# Total Nb. of potential leakages found: " << nbLeak << std::endl;
    verifMSICleanup();
    nbLeak = isw_and_4_shares();
    std::cout << "# Total Nb. of potential leakages found: " << nbLeak << std::endl;
    verifMSICleanup();
    return 0;
}

